services:
  - type: web
    name: markdeck
    buildCommand: npm install && npx puppeteer browsers install chrome && npm run build
    startCommand: npm run server
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: PUPPETEER_CACHE_DIR
        value: /opt/render/project/src/.cache/puppeteer
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
